# Generated by Django 4.1.7 on 2023-02-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='autumn_level',
            new_name='autumn',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='spring_level',
            new_name='spring',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='summer_level',
            new_name='summer',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='winter_level',
            new_name='winter',
        ),
    ]
